batch_size: 20000
dataset_path: null
device: cuda
grow_batch_size: false
init_reduced: true
init_sample_method: random
init_target_cp: 0.1
mace_predictor_path: /scratch/mk8347/data/acr_112025_mh1_stagetwo.model
mol_path: /scratch/mk8347/data/crystal_datasets/acridine/acridine_conformer.pt
mol_seed: 0
mols_to_sample: 1
num_samples: 2500
opt:
- anneal_lr: false
  compression_factor: 1.0
  convergence_eps: 0.001
  cutoff: 10
  enforce_reduced: true
  grad_norm_clip: 0.1
  init_lr: 0.05
  max_num_steps: 350
  optim_target: mace
  optimizer_func: rprop
  show_tqdm: true
  target_packing_coeff: null
  umbrella: false
  umbrella_epsilon: 7.5
  umbrella_sigma: 0.25
- anneal_lr: true
  compression_factor: 0.0
  convergence_eps: 1.0e-05
  cutoff: 10
  enforce_reduced: true
  grad_norm_clip: 0.1
  init_lr: 0.01
  max_num_steps: 150
  optim_target: mace
  optimizer_func: rprop
  show_tqdm: true
  target_packing_coeff: null
  umbrella: false
  umbrella_epsilon: 7.5
  umbrella_sigma: 0.25
opt_seed: 13
out_dir: /scratch/mk8347/csd_runs/datasets/acridine
run_name: may_acridine_sg14_zp2_13
sampling_mode: all
save_trajs: false
sgs_to_search:
- 14
target_identifier: null
target_path: null
uma_predictor_path: /scratch/mk8347/models/uma/esen_s.pt
umbrella_path: null
zp_to_search:
- 2
