wandb:
  username: mkilgour
  project_name: MXtalTools

paths:
  # where to look for configs
  local_config_path: '/home/mkilgour/MXtalTools/configs/' #'C:\Users\mikem\PycharmProjects\Python_Codes/MXtalTools/configs/'
  cluster_config_path: '/scratch/mk8347/mcrygan/configs/'

  # where to find datasets
  local_dataset_dir_path: '/home/mkilgour/crystal_datasets/' #"D:/crystal_datasets/"
  cluster_dataset_dir_path: '/scratch/mk8347/csd_runs/datasets/'

  # where to do the run
  local_workdir_path: '/home/mkilgour/mxtaltools_runs/'#  'C:/Users/mikem/crystals/CSP_runs/'
  cluster_workdir_path: '/scratch/mk8347/csd_runs/'

  # where to save model checkpoints # todo combine these
  local_checkpoint_dir_path: '/home/mkilgour/mxtaltools_runs/models/' #'C:/Users/mikem/crystals/CSP_runs/models/'
  cluster_checkpoint_dir_path: '/scratch/mk8347/csd_runs/models/'
  local_checkpoints_path: '/home/mkilgour/mxtaltools_runs/models/' #'C:\Users\mikem\crystals\CSP_runs\models/'
  cluster_checkpoints_path: '/scratch/mk8347/csd_runs/models/'

 # default config if not specified on command line
  yaml_path: "/home/mkilgour/MXtalTools/configs/experiments/dev.yaml" #'C:\Users\mikem\PycharmProjects\Python_Codes/MXtalTools/configs/experiments/dev.yaml'

  # paths for polymorph classification only
  local_classifier_results_path: 'D:\crystals_extra\classifier_training\results/'
  cluster_classifier_results_path: '/vast/mk8347/molecule_clusters/results/'

  local_classifier_trajectories_path: 'D:/crystals_extra/classifier_training/traj_pickles/'
  cluster_classifier_trajectories_path: '/vast/mk8347/molecule_clusters/traj_pickles/'