wandb:  # todo find a way to dummy this
  username: mkilgour
  project_name: MXtalTools

paths:
  # where to look for configs
  local_config_path: '../configs/test_configs'

  # where to find datasets
  local_dataset_dir_path: 'tests/datasets'

  # where to do the run
  local_workdir_path: 'tests/workdirs'

  # where to save model checkpoints
  local_checkpoint_dir_path: 'tests/checkpoints'
  local_checkpoints_path: 'tests/checkpoints'
