batch_size: 1000
dataset_path: null
device: cuda
force_restart_run: false
grow_batch_size: false
init_reduced: true
init_sample_method: random
init_sample_reduced: true
init_target_cp: wide
mace_predictor_path: null
mol_path: D:\crystal_datasets\conditional\priors\qm9_cluster_mols_chunk47.pt
mol_seed: 0
mols_to_sample: 0
num_samples: 10
opt:
- anneal_lr: false
  compression_factor: 1.0
  convergence_eps: 1.0e-05
  cutoff: 10
  enforce_reduced: true
  grad_norm_clip: 0.1
  init_lr: 0.05
  max_num_steps: 450
  optim_target: elj
  optimizer_func: rprop
  show_tqdm: false
  target_packing_coeff: null
  umbrella: false
- anneal_lr: false
  compression_factor: 0.0
  convergence_eps: 1.0e-05
  cutoff: 10
  enforce_reduced: true
  grad_norm_clip: 0.1
  init_lr: 0.01
  max_num_steps: 50
  optim_target: elj
  optimizer_func: rprop
  show_tqdm: false
  target_packing_coeff: null
  umbrella: false
opt_seed: 47
out_dir: D:/crystal_datasets/conditional/anchors
run_name: qm9c100k_chunk47
sampling_mode: all
save_trajs: false
score_model_checkpoint: null
sgs_to_search:
- 2
target_identifier: null
target_path: null
uma_predictor_path: null
umbrella_path: null
zp_to_search:
- 1
