#First, define the dataset by a series of conditions in format [key, type, [elements]]
#where type is in not_in or range and elements are [min, max], or a list of discrete values
#
#Then, specify the features which will be fed to models in training

seed: 1
max_dataset_length: 10000000
save_dataset: False
dataset_type: 'crystal'
regression_target: 'crystal_reduced_volume' # 'crystal_cell_volume' 'crystal_density' 'crystal_packing_coefficient'
single_molecule_dataset_identifier: null
test_fraction: 0.2
filter_protons: False

filter_polymorphs: False
filter_duplicate_molecules: False
filter_conditions: []