#First, define the dataset by a series of conditions in format [key, type, [elements]]
#where type is in not_in or range and elements are [min, max], or a list of discrete values
#
#Then, specify the features which will be fed to models in training

seed: 1
max_dataset_length: 1000000000
save_dataset: False
dataset_type: 'molecule'
regression_target: 'gap_energy' # 'crystal_reduced_cell_volume' 'crystal_density' 'crystal_packing_coefficient'
single_molecule_dataset_identifier: null
test_fraction: 0.2

filter_polymorphs: False
filter_duplicate_molecules: False
filter_protons: False
filter_conditions: [['molecule_num_atoms','range',[6,100]]] # at least 6 atoms so we miss e.g., methane

