device: cuda
mol_path: /scratch/mk8347/data/crystal_datasets/acridine/acr_newmodel_conformer.pt
dataset_path: /scratch/mk8347/data/crystal_datasets/acridine/campaigns/acr_zp1_sep30/seeds/seeds_TASK.pt
target_path: null
out_dir: /scratch/mk8347/data/crystal_datasets/acridine/campaigns/acr_zp1_sep30/runs
run_name: seeded_TASK
target_identifier: null
save_trajs: false
uma_predictor_path: null
mace_predictor_path: /scratch/mk8347/data/acr_newmodel.model
init_sample_method: data
init_reduced: true
force_restart_run: false
mol_seed: 0
opt_seed: 1300000000
sampling_mode: all
mols_to_sample: 1
num_samples: 20000
sgs_to_search:
- 14
zp_to_search:
- 1
batch_size: 96
grow_batch_size: true
init_target_cp: std
opt:
- optim_target: mace
  enforce_reduced: false
  compression_factor: 1.0
  cutoff: 10
  init_lr: 0.05
  convergence_eps: 0.01
  optimizer_func: rprop
  anneal_lr: false
  grad_norm_clip: 0.1
  show_tqdm: false
  max_num_steps: 350
  target_packing_coeff: null
  centroid_boundary: wrap
- optim_target: mace
  enforce_reduced: false
  compression_factor: 0.0
  cutoff: 10
  init_lr: 0.01
  convergence_eps: 0.0001
  optimizer_func: rprop
  anneal_lr: true
  grad_norm_clip: 0.1
  show_tqdm: false
  max_num_steps: 150
  target_packing_coeff: null
  centroid_boundary: wrap
oom_ceiling: true
coord_dir: /scratch/mk8347/data/crystal_datasets/acridine/campaigns/acr_zp1_sep30
coord_stream: seeded
coord_curate_every_s: 3600
coord_hop_wait_s: 7200
