# config.yaml - Sample configuration for single_point.py

# General output directory
output_dir: "./results"

# Cell Information:
# If "readcell_info" is true, the script will parse cell parameters from the input file header.
# Set to false to use the cell parameters provided here.
readcell_info: True
  #cell_params: [5.0, 5.0, 10.0, 90.0, 90.0, 120.0]  # [a, b, c, alpha, beta, gamma]

# Periodic Boundary Conditions (PBC)
pbc: true

# Calculator and Device Configuration
device: "cpu"              # Options: "gpu" or "cpu"
  #gpus: ["cuda:0"]           # List of GPU device identifiers if using GPU
model_paths:
  - "/scratch/al9500/APML/michael/mace-mpa-0-medium.model"  # Replace with the actual path to your trained model

# (Optional) Additional options can be added here as needed.
