machine: "local"  # or "cluster"
device: "cpu"  # or "cpu"
base_config_path: /experiments/base/regressor.yaml
dataset_name: mini_new_csd.pt
misc_dataset_name: /tests/datasets/misc_data_for_new_csd.npy' #

min_batch_size: 10
minimum_epochs: 2
max_epochs: 2 # 0 epochs takes us straight to sampling/evaluation (only implemented for GAN)

logger:
  sample_reporting_frequency: 1  # how often to do detailed reporting with figures
  run_name: regressor_test
  experiment_tag: test
